java:
  # aadIdentityName needs to be unset as it's not used in preview env yet
  aadIdentityName:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    REFORM_ENVIRONMENT: aat
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL : http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_API_URL : https://idam-api.aat.platform.hmcts.net
    FEES_API_URL : http://fees-register-api-aat.service.core-compute-aat.internal
    PRD_API_URL : http://rd-professional-api-aat.service.core-compute-aat.internal
    IDAM_S2S_URL : http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
