java:
  applicationPort: '9001'
  livenessPath: '/health'
  environment:
      APPLICATION_INSIGHTS_IKEY: '97f6a0e1-6be6-44b0-97bf-d03852b7791f'
      SLOT: 'PRODUCTION'
      REFORM_SERVICE_NAME: 'ps'
      REFORM_TEAM: 'finrem'
      APPINSIGHTS_INSTRUMENTATIONKEY : '97f6a0e1-6be6-44b0-97bf-d03852b7791f'
  image: 'https://hmcts.azurecr.io/hmcts/finrem-payment-service:latest'
  keyVaults:
    finrem:
      resourceGroup: finrem
      secrets:
        - finrem-payment-service-s2s-key
        - idam-secret
        - username-solicitor
        - password-solicitor
