java:
  aadIdentityName: finrem
  ingressHost: "finrem-ps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  applicationPort: '9001'
  livenessPath: '/health'
  image: 'https://hmcts.azurecr.io/hmcts/finrem-payment-service:latest'
  keyVaults:
    finrem:
      secrets:
        - finrem-payment-service-s2s-key
        - idam-secret
        - username-solicitor
        - password-solicitor
